/**
 * Routing-Controllers Authorization (BetterAuth)
 * Custom authorization checker and current user checker for routing-controllers
 * Uses BetterAuth session validation
 */

import { eq } from 'drizzle-orm';
import type { Request } from 'express';
import type { Action} from 'routing-controllers';
import { UnauthorizedError, ForbiddenError } from 'routing-controllers';
import { appConfig } from '../config/appConfig';
import { betterAuthClient } from '../infrastructure/better-auth.client';
import { dbClient } from '../infrastructure/db.client';
import { users } from '../schemas/user.schema';
import type { AuthUser } from '../types/auth.types';
// TODO: Implement BetterAuth client
// import { getAuthInstance } from '../infrastructure/better-auth.client';

/**
 * JWT Payload interface for test token extraction
 * Defines the shape of tokens generated by createTestUser in test-helpers.ts
 */
interface JWTPayload {
  sub: string;
  email?: string;
}

/**
 * Extended Request interface with auth properties
 * Temporarily extends Request until proper type augmentation is set up
 */
interface AuthRequest extends Request {
  user?: AuthUser;
  session?: {
    id: string;
    userId: string;
    expiresAt: Date;
  };
}

/**
 * Authorization checker for routing-controllers
 * Validates BetterAuth session and checks user roles/permissions
 *
 * Used by routing-controllers @Authorized decorator
 * 
 * Supports both:
 * 1. BetterAuth sessions via betterAuthClient.api.getSession()
 * 2. Direct JWT tokens (for testing) - extracts user ID from token
 */
export async function authorizationChecker(
   action: Action,
   roles: string[]
): Promise<boolean> {
   try {
     const request = action.request as AuthRequest;

      // BetterAuth automatically extracts Bearer token from Authorization header
      if (!betterAuthClient) {
        return false;
      }
      const session = await betterAuthClient.api.getSession({
       headers: request.headers,
     });

     let userId: string | undefined;
     
     if (session) {
       // BetterAuth session found
       userId = session.user.id as string;
      } else {
         // Try to extract JWT token directly (for testing)
         const authHeader = request.headers.authorization;
         if (authHeader && authHeader.startsWith('Bearer ')) {
           const token = authHeader.substring(7);
           try {
             const { verify } = await import('jsonwebtoken');
             const decoded = verify(token, appConfig.BETTER_AUTH_SECRET) as JWTPayload;
             userId = decoded.sub;
           } catch {
             // Invalid or expired token
             throw new UnauthorizedError('Invalid or expired token');
           }
         }
      }

      if (!userId) {
        throw new UnauthorizedError('Authentication required');
      }

      // Fetch full user from database to get role and status
      const user = await dbClient.query.users.findFirst({
        where: eq(users.id, userId),
      });

      if (!user) {
        throw new UnauthorizedError('User not found');
      }

      // Check user status - inactive or suspended users cannot login
      if (user.status === 'inactive' || user.status === 'suspended') {
        throw new UnauthorizedError('User account is inactive or suspended');
      }

     // Attach user to request (for currentUserChecker)
     request.user = {
       id: user.id,
       email: user.email,
       name: user.name,
       role: user.role,
       status: user.status,
       emailVerified: user.emailVerified,
       createdAt: user.createdAt,
       lastLoginAt: user.lastLoginAt,
     } as AuthUser;

     // Attach session to request
     if (session) {
       request.session = {
         id: session.session.id as string,
         userId: user.id,
         expiresAt: session.session.expiresAt as Date,
       };
     }

      // If no specific roles required, just check if authenticated
      if (!roles || roles.length === 0) {
        return true;
      }

      // Check if user has required role
      // 403 Forbidden: User is authenticated but lacks required role
      if (!roles.includes(user.role)) {
        throw new ForbiddenError('User does not have required role');
      }

      return true;
    } catch (error) {
      // Re-throw UnauthorizedError to preserve 401 status
      if (error instanceof UnauthorizedError) {
        throw error;
      }
      // For other errors, return false (which routing-controllers treats as 403)
      return false;
    }
}

/**
 * Current user checker for routing-controllers
 * Returns current authenticated user for use in controllers
 *
 * Used by routing-controllers @CurrentUser decorator
 * 
 * Supports both:
 * 1. BetterAuth sessions via betterAuthClient.api.getSession()
 * 2. Direct JWT tokens (for testing) - extracts user ID from token
 */
export async function currentUserChecker(
   action: Action
): Promise<AuthUser | undefined> {
   try {
     const request = action.request as AuthRequest;

      // BetterAuth automatically extracts Bearer token from Authorization header
      if (!betterAuthClient) {
        return undefined;
      }
      const session = await betterAuthClient.api.getSession({
        headers: request.headers,
      });

     let userId: string | undefined;
     
     if (session) {
       // BetterAuth session found
       userId = session.user.id as string;
      } else {
        // Try to extract JWT token directly (for testing)
        const authHeader = request.headers.authorization;
        if (authHeader && authHeader.startsWith('Bearer ')) {
          const token = authHeader.substring(7);
          try {
            const { verify } = await import('jsonwebtoken');
            const decoded = verify(token, appConfig.BETTER_AUTH_SECRET) as JWTPayload;
            userId = decoded.sub;
          } catch {
            // Invalid or expired token
            return undefined;
          }
        }
      }

      if (!userId) {
        return undefined;
      }

      // Fetch full user from database to get role and status
      const user = await dbClient.query.users.findFirst({
        where: eq(users.id, userId),
     });

     if (!user || user.status === 'inactive' || user.status === 'suspended') {
       return undefined;
     }

     return {
       id: user.id,
       email: user.email,
       name: user.name,
       role: user.role,
       status: user.status,
       emailVerified: user.emailVerified,
       createdAt: user.createdAt,
       lastLoginAt: user.lastLoginAt,
     } as AuthUser;

      return undefined;
    } catch (_error) {
      return undefined;
    }
}
